spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.16:3306/test
    username: root
    password: redshiproot

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show_sql: true

    hibernate:
      ddl-auto: update
      #어플리케이션 시점에 테이블 다지우고 jpa엔티티 정보로 생성함
    properties:
      hibernate:
        #프린트로 찍음
        format_sql: true

  web:
    resources:
      static-locations: classpath:/static/


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: debug
#로거로 찍음
#pstm의 특성을 잘 가져가야만 한다

thymeleaf:
  prefix=classpath: templates/
  suffix: .html
  check-template-location: true
  cache: false
  mvc:
    static-path-pattern: "/static/**"


